#!/bin/bash
# OpenTenBase APT 仓库一键安装脚本
# Usage: curl -sSL https://github.com/muzimu217/opentenbase-deb/releases/latest/download/setup-apt.sh | sudo bash

set -e

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# 配置
REPO_URL="https://github.com/muzimu217/opentenbase-deb/releases/latest/download"
GPG_KEY_URL="${REPO_URL}/opentenbase-gpg-key.asc"
KEYRING_PATH="/usr/share/keyrings/opentenbase-archive-keyring.gpg"
SOURCES_LIST="/etc/apt/sources.list.d/opentenbase.list"

# 日志函数
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_step() {
    echo -e "${BLUE}[STEP]${NC} $1"
}

# 检查 root 权限
check_root() {
    if [ "$(id -u)" -ne 0 ]; then
        log_error "此脚本需要 root 权限运行"
        echo "请使用: sudo bash $0"
        exit 1
    fi
}

# 检测操作系统
detect_os() {
    log_step "检测操作系统..."

    if [ ! -f /etc/os-release ]; then
        log_error "无法检测操作系统版本"
        exit 1
    fi

    . /etc/os-release

    case "$ID" in
        ubuntu)
            OS="ubuntu"
            CODENAME="${UBUNTU_CODENAME:-$VERSION_CODENAME}"
            VERSION_ID_SHORT="${VERSION_ID}"

            # 验证支持的版本
            case "$VERSION_ID" in
                20.04|22.04|24.04)
                    ;;
                *)
                    log_warn "Ubuntu $VERSION_ID 未经测试，可能存在问题"
                    ;;
            esac
            ;;
        debian)
            OS="debian"
            CODENAME="$VERSION_CODENAME"
            VERSION_ID_SHORT="$VERSION_ID"

            # 验证支持的版本
            case "$VERSION_ID" in
                11|12)
                    ;;
                *)
                    log_warn "Debian $VERSION_ID 未经测试，可能存在问题"
                    ;;
            esac
            ;;
        linuxmint)
            # Linux Mint 基于 Ubuntu
            OS="ubuntu"
            case "$VERSION_ID" in
                21*) CODENAME="jammy" ;;
                22*) CODENAME="noble" ;;
                *)   CODENAME="jammy" ;;
            esac
            VERSION_ID_SHORT="$VERSION_ID"
            log_info "检测到 Linux Mint $VERSION_ID，使用 Ubuntu $CODENAME 源"
            ;;
        pop)
            # Pop!_OS 基于 Ubuntu
            OS="ubuntu"
            case "$VERSION_ID" in
                22.04) CODENAME="jammy" ;;
                24.04) CODENAME="noble" ;;
                *)     CODENAME="jammy" ;;
            esac
            VERSION_ID_SHORT="$VERSION_ID"
            log_info "检测到 Pop!_OS $VERSION_ID，使用 Ubuntu $CODENAME 源"
            ;;
        *)
            log_error "不支持的操作系统: $ID"
            echo "支持的系统: Ubuntu 20.04/22.04/24.04, Debian 11/12"
            exit 1
            ;;
    esac

    log_info "检测到: $OS $VERSION_ID_SHORT ($CODENAME)"
}

# 检查必要工具
check_dependencies() {
    log_step "检查必要工具..."

    local missing=()

    for cmd in curl gpg apt-get; do
        if ! command -v "$cmd" &> /dev/null; then
            missing+=("$cmd")
        fi
    done

    if [ ${#missing[@]} -gt 0 ]; then
        log_error "缺少必要工具: ${missing[*]}"
        log_info "请先安装: apt-get install -y ${missing[*]}"
        exit 1
    fi
}

# 添加 GPG 密钥
add_gpg_key() {
    log_step "添加 GPG 密钥..."

    # 创建 keyrings 目录
    mkdir -p /usr/share/keyrings

    # 下载并添加 GPG 密钥
    if curl -fsSL "$GPG_KEY_URL" | gpg --dearmor -o "$KEYRING_PATH" 2>/dev/null; then
        chmod 644 "$KEYRING_PATH"
        log_info "GPG 密钥已添加到: $KEYRING_PATH"
    else
        log_error "GPG 密钥下载失败"
        echo "请检查网络连接或手动下载: $GPG_KEY_URL"
        exit 1
    fi
}

# 配置 APT 源
configure_repo() {
    log_step "配置 APT 源..."

    # 备份现有配置
    if [ -f "$SOURCES_LIST" ]; then
        cp "$SOURCES_LIST" "${SOURCES_LIST}.bak"
        log_info "已备份现有配置到: ${SOURCES_LIST}.bak"
    fi

    # 写入新的源配置
    cat > "$SOURCES_LIST" << EOF
# OpenTenBase APT Repository
# Generated by setup-apt.sh on $(date -u '+%Y-%m-%d %H:%M:%S UTC')
deb [signed-by=$KEYRING_PATH] https://muzimu217.github.io/opentenbase-deb/apt $CODENAME main
EOF

    chmod 644 "$SOURCES_LIST"
    log_info "APT 源已配置到: $SOURCES_LIST"
}

# 更新软件包列表
update_package_list() {
    log_step "更新软件包列表..."

    if apt-get update -qq 2>/dev/null; then
        log_info "软件包列表已更新"
    else
        log_warn "软件包列表更新失败，可能需要手动运行: apt-get update"
    fi
}

# 显示安装说明
show_install_info() {
    echo ""
    echo "========================================"
    echo -e "${GREEN}  OpenTenBase APT 仓库配置完成！${NC}"
    echo "========================================"
    echo ""
    echo "现在可以使用以下命令安装 OpenTenBase:"
    echo ""
    echo "  # 安装完整包（推荐）"
    echo "  sudo apt install opentenbase"
    echo ""
    echo "  # 或单独安装组件"
    echo "  sudo apt install opentenbase-server"
    echo "  sudo apt install opentenbase-client"
    echo "  sudo apt install opentenbase-contrib"
    echo ""
    echo "  # 查看可用版本"
    echo "  apt-cache search opentenbase"
    echo ""
    echo "  # 安装后快速开始"
    echo "  opentenbase-ctl init    # 初始化集群"
    echo "  opentenbase-ctl start   # 启动所有节点"
    echo "  opentenbase-ctl status  # 检查状态"
    echo ""
    echo "========================================"
}

# 主函数
main() {
    echo "========================================"
    echo "  OpenTenBase APT 仓库安装脚本"
    echo "========================================"
    echo ""

    check_root
    detect_os
    check_dependencies
    add_gpg_key
    configure_repo
    update_package_list
    show_install_info
}

# 执行主函数
main "$@"
